"""update tables structure for user, card and transaction

Revision ID: 89e1db4c7f57
Revises: 8e59255f69f4
Create Date: 2025-10-23 21:30:43.199660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e1db4c7f57'
down_revision: Union[str, Sequence[str], None] = '8e59255f69f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('cvv2', sa.String(length=4), nullable=False))
    op.add_column('cards', sa.Column('expire_date', sa.String(length=5), nullable=False))
    op.add_column('cards', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('national_code', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_constraint(op.f('users_national_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['national_code'])
    op.drop_column('users', 'national_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('national_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_national_id_key'), 'users', ['national_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'national_code')
    op.drop_column('cards', 'created_at')
    op.drop_column('cards', 'is_active')
    op.drop_column('cards', 'expire_date')
    op.drop_column('cards', 'cvv2')
    # ### end Alembic commands ###
