"""update tables structure for user, card and transaction

Revision ID: df04dba0206c
Revises: 89e1db4c7f57
Create Date: 2025-10-23 21:34:30.227104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df04dba0206c'
down_revision: Union[str, Sequence[str], None] = '89e1db4c7f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'description')
    # ### end Alembic commands ###
